remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
  - COPYING.md
  - HISTORY.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

theme: jekyll-theme-slate